# Generated by Django 5.1.2 on 2024-10-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntiHero',
            fields=[
                ('antihero_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('history', models.CharField(max_length=500)),
            ],
        ),
    ]
